### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by bidongqinxian** [cvlab-tohoku/Dense-CoAttention-Network#1]
Hello,can you provide the pretrained model to me? I want to test the model directly.Thank you!

**Comment by kienduynguyen** [comment]
Dear @bidongqinxian ,

Sorry for my late reply. Do you still need the pretrained model?

**Comment by bidongqinxian** [comment]
I appreciate if you could @kienduynguyen

**Comment by kienduynguyen** [comment]
Dear @bidongqinxian ,
We added demo code to our github repo.
