### ISSUE TITLE
img_mask

### ISSUE THREAD

**Issue by mutouretu** [cvlab-tohoku/Dense-CoAttention-Network#11]
Hi @kienduynguyen , there is a problem when I ran the program and the link is:
[https://github.com/cvlab-tohoku/Dense-CoAttention-Network/blob/master/train.py#L47](url)

The error information is:
    img, img_mask = img_info
ValueError: too many values to unpack (expected 2)

My torch version is 1.1.0. 
Did you meet this problem before or can you please tell me how to solve it? Thank you!

**Comment by kienduynguyen** [comment]
Hi @mutouretu! If you use Resnet features, so there is no img_mask. I already updated the Resnet dataset to make it generate None for img_mask. Please check it again!

**Comment by mutouretu** [comment]
OK，thank you!

**Comment by mutouretu** [comment]
Hi @kienduynguyen! There is still some problem of the modification. The default_collate verifies if the arguments are iterable, and the None type causes an error. I think an empty list or tuple is better.

Please check it and the link is:
https://github.com/cvlab-tohoku/Dense-CoAttention-Network/blob/master/dense_coattn/data/dataloader.py#L127

Thank you!
