### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by UPCLJ** [cvlab-tohoku/Dense-CoAttention-Network#12]
hello,I have  some questions after running your answer.py. and ensemble.py. I have got the .json file with question_id and answer. But there's nothing like the percentage that you get after running train.py. What can I do for getting the percentage result? look forward to hearing from you.

**Comment by kienduynguyen** [comment]
You can load the json file to a variable and follow this code:

```
        vqa = VQA(opt.ann_file, opt.ques_file)
	vqa.load_result(result)
	vqa_eval = VQAEval(vqa)
	vqa_eval.evaluate()
	vqa_eval.compute_entropy()

	print("\n")
	print(">>>> Overall Accuracy is: %.02f\n" %(vqa_eval.accuracy["overall"]))
	print(">>>> Per Question Type Accuracy & Entropy is the following:")
	for quesType in vqa_eval.accuracy["per_questype"]:
		print("%s : %.02f, %.04f" %(quesType, 
			vqa_eval.accuracy["per_questype"][quesType], 
			vqa_eval.entropy["per_questype"][quesType]))
	print("\n")
	print(">>>> Per Answer Type Accuracy & Entropy is the following:")
	for ansType in vqa_eval.accuracy["per_anstype"]:
		print("%s : %.02f, %.04f" %(ansType, 
			vqa_eval.accuracy["per_anstype"][ansType],
			vqa_eval.entropy["per_anstype"][ansType]))
	print("\n")
	json.dump({"accuracy": vqa_eval.accuracy, "entropy": vqa_eval.entropy},
			  open(os.path.join(opt.result_file, '{}_acc.json'.format(opt.model)), "w"))
```

**Comment by UPCLJ** [comment]
more thanks.
vqa = VQA(opt.ann_file, opt.ques_file) :the test and test-dev dataset don't have ann_file,how to use this code.
vqa.load_result(result):the result is loaded json file?

**Comment by kienduynguyen** [comment]
Please use the evaluation server (evalai) for test set :D

**Comment by UPCLJ** [comment]
https://github.com/GT-Vision-Lab/VQA/blob/master/PythonEvaluationTools/vqaEvalDemo.py
sorry,I don't understand.could you please give me more information?

**Comment by kienduynguyen** [comment]
Please check this: https://evalai.cloudcv.org/
