### ISSUE TITLE
KeyError in model

### ISSUE THREAD

**Issue by annieU** [cvlab-tohoku/Dense-CoAttention-Network#3]
Hi, I trained the model followed `train.py` and want to get the answers from `answer.py`, but when I ran it, I got an error like:
```
Initializing Dynamic LSTM...
Freezing resnet152 ...
Loading model from checkpoint at /home/annie/Dense-CoAttention-Network/VQA/model/DCN1.pt
Traceback (most recent call last):
  File "answer.py", line 156, in <module>
    main(args)
  File "answer.py", line 109, in main
    model.load_state_dict(checkpoint["model"])
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "lang_extract.rnn.weight_ih_l1" in state_dict'
```
Could you tell me what's wrong with it?

**Comment by kienduynguyen** [comment]
Hi @annieU ,

In the ```train.py``` file, I set the ```num_layers=2```, and it should be the same in the ```answer.py``` file. Your error is that you set the ```num_layers=1``` in the ```answer.py``` file.

**Comment by annieU** [comment]
@kienduynguyen Thank you for your reply! The problem has been solved.
