### ISSUE TITLE
single_machine_demo.py gives blank window for me?

### ISSUE THREAD

**Issue by hughperkins** [cvlab-tohoku/Dense-CoAttention-Network#4]
<img width="805" alt="screen shot 2018-11-09 at 10 56 49 am" src="https://user-images.githubusercontent.com/123560/48255887-426e4c80-e40e-11e8-82f6-c8fad1566703.png">

(running on Mac OS X)

**Comment by hughperkins** [comment]
Oh, I see. Have to go to 'File' menu, and upload one :)

**Comment by kienduynguyen** [comment]
Hi @hughperkins ,
Thanks for interested in our work! If you have any question, please feel free to ask us.
