### ISSUE TITLE
Single_machine_demo.py gives attribute error

### ISSUE THREAD

**Issue by Prudhvinik1** [cvlab-tohoku/Dense-CoAttention-Network#5]
Building model...
Loading pretrained word vectors from /home/prudhvik/data/glove_840B.pt
Loading model from checkpoint at /home/prudhvik//models/trained.pt
Traceback (most recent call last):
  File "test_dcn.py", line 202, in <module>
    model, idx2ans, word2idx = load_pretrained_model(opt)
  File "test_dcn.py", line 121, in load_pretrained_model
    model.cuda(opt['gpus'][0])
AttributeError: 'dict' object has no attribute 'cuda'

I am unable to resolve it.

**Comment by kienduynguyen** [comment]
I think you save model's state dict instead of model object. In case of saving model state dict, you need to initialize model object first and load state dict to the model. Or, you can directly save model object.

**Comment by Prudhvinik1** [comment]
How do I create a model object? I am not sure what to give the parameters for num_ans?

model = DCN(opt, num_ans).

And also I haven't changed the way the model is being saved. I am merely running a trained model with the single_machine_demo.py file

**Comment by kienduynguyen** [comment]
Please try torch.save(model) to save the model object.

**Comment by Prudhvinik1** [comment]
Thanks for the help I created a model object and was able to run it.

**Comment by Prudhvinik1** [comment]
Also can you please provide the visualization of images and questions with attention? Like the one in the paper. 

May I know how to get the accuracies after running answer.py file using vqa v1 dataset.

**Comment by kienduynguyen** [comment]
The attention generation is in Drawer object in utils.py
You can use the evaluation tool 'vqa_eval' provided by the authors to test it
