### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by UPCLJ** [cvlab-tohoku/Dense-CoAttention-Network#8]
Hello, I want to know where the "rcnn_trainval.pt","rcnn_trainval.h5","rcnn_test.pt","rcnn_test.h5" from the class RCNNDataset from dataset.py(dense_coattn/data/). Are they from 'prepross/load_features.ipynb'?  But in this program they are named trainval_images.h5,trainval_image.pt,test_images.h5,test_images.pt.
I have renamed them. However, when I run the train.py, it will get stack on “for I, batch in enumerate(dataloader)” from def trainEpoch.
I think it might be a dataset problem. I hope you can help me. Thanks for your reading.

**Comment by kienduynguyen** [comment]
Hi,

Sorry for the inconvenient but you should rename them (I will make it consistent later). I think you have problem with dataloader. One possible solution is to set the --use-thread as True. Another solution is to use the DataLoader provided by Pytorch 1.0 (from torch.utils.data import DataLoader) but remember to remove the use_thread option of DataLoader in main function of train.py and use our default_collate function.

**Comment by kienduynguyen** [comment]
Hi @UPCLJ ,

I push the fixed code. Please check that!

**Comment by UPCLJ** [comment]
Thank you for your reply.I'm sorry for not seeing your message until now​.I will try to run the train.py again at your suggestion.



------------------ 原始邮件 ------------------


发件人: "Nguyen Duy Kien"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 晚上8:47
收件人: "cvlab-tohoku/Dense-CoAttention-Network"<Dense-CoAttention-Network@noreply.github.com>;
抄送: "美羊羊"<284731553@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cvlab-tohoku/Dense-CoAttention-Network] dataset (#8)




Hi,
 
Sorry for the inconvenient but you should rename them (I will make it consistent later). I think you have problem with dataloader. One possible solution is to set the --use-thread as True. Another solution is to use the DataLoader provided by Pytorch 1.0 (from torch.utils.data import DataLoader) but remember to remove the use_thread option of DataLoader in main function of train.py.

**Comment by UPCLJ** [comment]
Hello, I managed to get out of the code(train.py). But I have trouble with answer.py Help me,please.@kienduynguyen

**Comment by kienduynguyen** [comment]
Hi @UPCLJ ,

I already update the code in answer.py.
